/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    fontSize: {
      xs: 'var(--font-size-xm)',
      sm: 'var(--font-size-sm)',
      base: 'var(--font-size-base)',
      lg: 'var(--font-size-lg)',
      xl: 'var(--font-size-xl)',
      '2xl': 'var(--font-size-2xl)',
      '3xl': 'var(--font-size-3xl)',
      '4xl': 'var(--font-size-4xl)',
      '5xl': 'var(--font-size-4xl)',
      '6xl': 'var(--font-size-6xl)',
      '7xl': 'var(--font-size-7xl)',
    },
    fontFamily: {
      sans: [
        'Jost',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'BlinkMacSystemFont',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
      ],
      jost: ['Jost', 'sans-serif'],
      gangster: 'Gangster',
    },
    extend: {
      borderRadius: {
        '4xl': '2rem',
      },
      colors: {
        'md-transparent': 'var(--md-transparent)',
        'md-bg': 'var(--md-bg)',
        'md-white': 'var(--md-white)',
        'md-black': 'var(--md-black)',
        'md-grey': 'var(--md-grey)',
        'md-dark-red': 'var(--md-dark-red)',
        'md-lilac': {
          100: 'var(--md-lilac-100)',
          200: 'var(--md-lilac-200)',
          300: 'var(--md-lilac-300)',
          400: 'var(--md-lilac-400)',
        },
        'md-astronaut': {
          100: 'var(--md-astronaut-100)',
          200: 'var(--md-astronaut-200)',
          300: 'var(--md-astronaut-300)',
          400: 'var(--md-astronaut-400)',
        },
        'md-flamingo': {
          100: 'var(--md-flamingo-100)',
          200: 'var(--md-flamingo-200)',
          300: 'var(--md-flamingo-300)',
          400: 'var(--md-flamingo-400)',
        },
      },
      lineHeight: {
        'md-0': 'var(--line-height-0)',
        'md-1': 'var(--line-height-1)',
        'md-2': 'var(--line-height-2)',
        'md-3': 'var(--line-height-3)',
        'md-4': 'var(--line-height-4)',
        'md-5': 'var(--line-height-5)',
        'md-6': 'var(--line-height-6)',
        'md-7': 'var(--line-height-7)',
      },
      letterSpacing: {
        'md-0': 'var(--letter-spacing-1)',
        'md-1': 'var(--letter-spacing-2)',
        'md-2': 'var(--letter-spacing-3)',
      },
    },
  },
  plugins: [],
};
